environment:
  PROJECT_NAME: pmdk-rs
  PMDK_VERSION: 1.4
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly
    - TARGET: i686-pc-windows-msvc
      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: i686-pc-windows-gnu
      CHANNEL: nightly

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV
  - choco install -y doxygen.portable
  - appveyor DownloadFile https://github.com/pmem/pmdk/releases/download/%PMDK_VERSION%/pmdk-%PMDK_VERSION%-win-x64-Setup.msi
  - msiexec /i pmdk-%PMDK_VERSION%-win-x64-Setup.msi ACCEPT=YES /qr+
  - ps: ci\set-pmdk-environment.ps1

build: false

test_script:
  - cargo build --verbose --manifest-path pmem-sys/Cargo.toml
  - cargo test --verbose --manifest-path pmem-sys/Cargo.toml
